#!/bin/sh

args() {
    sed -n 's/^'"$1"' *= *\(.*\) *$/\1/p' "$HOME/.monitors"
}

monitors() {
		xrandr | awk '/ connected/{print $1}'
}

disconnected_monitors() {
		xrandr | awk '/ disconnected/{print $1}'
}

# -a also includes connected and enabled monitors
sync() {
    all=
    [ "$1" = -a ] && all=1
    xrandr_args=
    for monitor in `monitors`; do
				xrandr_args="$xrandr_args --output $monitor --auto `args "$monitor"`"
				echo "+$monitor"
    done
		for monitor in `disconnected_monitors`; do
				xrandr_args="$xrandr_args --output $monitor --off"
				echo "-$monitor"
		done
    if [ "$xrandr_args" ]; then
        echo "xrandr$xrandr_args" >&2
        xrandr $xrandr_args
    fi
    return 0
}

sh -x -c "`args before`"
sync $1
sh -x -c "`args after`"

